<html>
  <head>
    <title>femtolisp tutorial</title>
      <meta http-equiv= 'Content-Type'
         content= 'text/html; charset=utf-8' />
   </head>
 <body>
   <form name='form' method='get'>
      <input type='text' name='temp'>
      <input type='submit' name='btn' value='send'>
  </form>
  <p>La réponse est  
> (let ( (str (os.getenv "QUERY_STRING")))
>    (if str (princ str) (princ "vide"))
>       (newline))
  </p>
</body>
</html>

